// <auto-generated />
using System;
using LaptimeBaseAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LaptimeBaseAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250515182324_RemoveCircularReference")]
    partial class RemoveCircularReference
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.15");

            modelBuilder.Entity("LaptimeBaseAPI.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("class");

                    b.HasKey("Id");

                    b.ToTable("car");
                });

            modelBuilder.Entity("LaptimeBaseAPI.Models.Laptime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("session_id");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("team_id");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("TEXT")
                        .HasColumnName("time");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("TeamId");

                    b.ToTable("laptime");
                });

            modelBuilder.Entity("LaptimeBaseAPI.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AmbientTemp")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ambient_temp");

                    b.Property<DateTime>("HeldAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("held_at");

                    b.Property<int>("TrackId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("track_id");

                    b.Property<int>("TrackTemp")
                        .HasColumnType("INTEGER")
                        .HasColumnName("track_temp");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.ToTable("session");
                });

            modelBuilder.Entity("LaptimeBaseAPI.Models.Team", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<int>("CarId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("car_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("UserId", "CarId");

                    b.HasIndex("CarId");

                    b.ToTable("team");
                });

            modelBuilder.Entity("LaptimeBaseAPI.Models.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("track");
                });

            modelBuilder.Entity("LaptimeBaseAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_admin");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("user");
                });

            modelBuilder.Entity("LaptimeBaseAPI.Models.Laptime", b =>
                {
                    b.HasOne("LaptimeBaseAPI.Models.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaptimeBaseAPI.Models.Team", "Team")
                        .WithMany("Laptimes")
                        .HasForeignKey("TeamId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("LaptimeBaseAPI.Models.Session", b =>
                {
                    b.HasOne("LaptimeBaseAPI.Models.Track", "Track")
                        .WithMany("Sessions")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("LaptimeBaseAPI.Models.Team", b =>
                {
                    b.HasOne("LaptimeBaseAPI.Models.Car", "Car")
                        .WithMany("Teams")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaptimeBaseAPI.Models.User", "User")
                        .WithMany("Teams")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LaptimeBaseAPI.Models.Car", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("LaptimeBaseAPI.Models.Team", b =>
                {
                    b.Navigation("Laptimes");
                });

            modelBuilder.Entity("LaptimeBaseAPI.Models.Track", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("LaptimeBaseAPI.Models.User", b =>
                {
                    b.Navigation("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
